[package]
name = "spuz_ir"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
serde = { workspace = true }

[lints]
workspace = true
